export const TRAER_TODAS = 'tareas_traer_tareas'
export const CAMBIO_USUARIO_ID = 'cambio_usuario_id'
export const CAMBIO_TITULO = 'cambio_titulo'
export const AGREGADA = 'tareas_agregada'
export const CARGANDO = 'tareas_cargando'
export const ERROR = 'tareas_error'
